# Generated by Django 4.1.3 on 2023-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
